services:
  - type: web
    name: myapi
    repo: https://github.com/pai801/myapi
    branch: main
    runtime: docker
    plan: free
    region: singapore
    buildCommand: ""
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Shanghai
      - key: SESSION_SECRET
        value: session-sec
    healthCheckPath: /api/status
    autoDeploy: true
